In [2]:
import numpy as np

In [11]:
i = np.array([0, 1, 2])
print(i)

[0 1 2]


In [17]:
k = np.array([1,2,3], dtype = "float64")
k

array([1., 2., 3.])

In [19]:
i + k

array([1., 3., 5.])

In [23]:
print((i+k).dtype)

float64


In [26]:
print((i+k).itemsize)
print((i+k).shape)
print((i+k).size)

8
(3,)
3


In [27]:
j = np.arange(16).reshape(4,4)
print(j)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [33]:
print(i)
print(np.resize(i, (1,)))
print(np.resize(i, (1,1)))
print(np.resize(i, (1,2)))
print(np.resize(i, (2,1)))
print(np.resize(i, (3,3)))

[0 1 2]
[0]
[[0]]
[[0 1]]
[[0]
 [1]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [41]:
i.resize((3,3),refcheck = False)
print(i)

[[0 1 2]
 [0 0 0]
 [0 0 0]]


In [56]:
ones = np.ones((5,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
zeros = np.zeros((5,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.diag(j)

array([ 0,  5, 10, 15])

In [54]:
np.repeat([4,3,2], 2)

array([4, 4, 3, 3, 2, 2])

In [66]:
np.hstack([ones, zeros])

array([[1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0.]])

In [67]:
zeros = np.resize(zeros,(5,5))
np.vstack([ones, zeros])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [79]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x + y

array([5, 7, 9])

In [72]:
x - y

array([-3, -3, -3])

In [73]:
x / y

array([0.25, 0.4 , 0.5 ])

In [75]:
x // 2

array([0, 1, 1], dtype=int32)

In [76]:
x ** 2

array([1, 4, 9])

In [80]:
x.dot(y)

32

In [78]:
x * y

array([ 4, 10, 18])

In [83]:
j.shape

(4, 4)

In [87]:
print(j)
print(j.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [88]:
j.astype('f')

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]], dtype=float32)

In [89]:
j.sum()

120

In [92]:
print(j.sum(axis = 0))
print(j.sum(axis = 1))

[24 28 32 36]
[ 6 22 38 54]


In [91]:
j.max()

15

In [93]:
j.min()

0

In [95]:
j.argmax()

15

In [97]:
j.mean()

7.5

In [98]:
j.std()

4.6097722286464435

In [112]:
print(j, '\n')
print(j[0:1], '\n')
print(j[0:1, 1:3], '\n')
print(j[1:3, 1:3], '\n')
print(j[:, 1:3], '\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[0 1 2 3]] 

[[1 2]] 

[[ 5  6]
 [ 9 10]] 

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]] 



In [121]:
print(j[-1][-1], '\n')
print(j[-1, -1], '\n')

15 

15 



In [130]:
print(j[1][1:4:2], '\n')
print(j[1, 1:4:2], '\n')
print(j[1, 4:0:-2], '\n')

[5 7] 

[5 7] 

[7 5] 



In [9]:
three_dim = np.arange(12).reshape(3,4)
three_dim

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
for row in three_dim:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [12]:
for element in three_dim.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11


In [13]:
three_dim.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
np.r_[1:4, 0]

array([1, 2, 3, 0])

In [24]:
np.c_[1:4]


array([[1],
       [2],
       [3]])

In [31]:
np.hsplit(three_dim, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [33]:
np.hsplit(three_dim, (3, 4))

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10]]),
 array([[ 3],
        [ 7],
        [11]]),
 array([], shape=(3, 0), dtype=int32)]

In [35]:
test = three_dim
test is three_dim

True

In [37]:
test = three_dim.view()
test is three_dim

False

In [ ]:
new_array = three_dim.copy()
print(new_array is three_dim)
print(new_array is three_dim)

False
